In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
#converting categorical to numerical value
dataset=pd.get_dummies(dataset,dtype=int, drop_first=True)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [6]:
# Independent Variables (Features)
indep = dataset[[
    "age", "bp", "al", "su", "bgr", "bu", "sc", "sod", "pot", "hrmo",
    "pc_normal", "pcc_present", "ba_present", "htn_yes", "dm_yes", "cad_yes",
    "appet_yes", "pe_yes", "ane_yes"
]]

# Dependent Variable (Target)
dep = dataset["classification_yes"]

In [7]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [8]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report

# Define the parameter grid for GridSearchCV
param_grid = {
    'alpha': [0.1, 0.5, 1.0, 1.5, 2.0],  # Smoothing parameter
    'binarize': [0.0, 0.5, 1.0]  # Threshold for binarizing (if not already binary)
}

# Set up the GridSearchCV object
grid = GridSearchCV(BernoulliNB(), param_grid, 
                    refit=True, verbose=3, n_jobs=-1, scoring='f1_weighted')

# Fitting the model for grid search
grid.fit(X_train, y_train)

# To see the best parameters and the best estimator
print("Best Parameters:", grid.best_params_)
print("Best Estimator:", grid.best_estimator_)

Fitting 5 folds for each of 15 candidates, totalling 75 fits
Best Parameters: {'alpha': 0.1, 'binarize': 0.0}
Best Estimator: BernoulliNB(alpha=0.1)

In [9]:
# Print the best parameters after tuning
print("Best Parameters:", grid.best_params_)

# Store cross-validation results
cv_results = grid.cv_results_
# Uncomment to print all cross-validation results
# print(cv_results)

# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)

# Using the final best fit model to test X_test
grid_predictions = grid.predict(X_test)

Best Parameters: {'alpha': 0.1, 'binarize': 0.0}

In [10]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

In [11]:
print(cm)

[[51  0]
 [ 8 74]]

In [12]:
# Generate classification report
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [13]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.86      1.00      0.93        51
           1       1.00      0.90      0.95        82

    accuracy                           0.94       133
   macro avg       0.93      0.95      0.94       133
weighted avg       0.95      0.94      0.94       133

In [14]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

np.float64(0.9634146341463414)

In [15]:
print(cm)

[[51  0]
 [ 8 74]]

In [16]:
table=pd.DataFrame.from_dict(re)

In [17]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,param_binarize,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.011709,0.004898,0.010910,0.003153,0.1,0.0,"{'alpha': 0.1, 'binarize': 0.0}",0.908877,0.962264,0.925524,0.962573,0.981217,0.948091,0.026664,1
1,0.009282,0.002946,0.009818,0.004041,0.1,0.5,"{'alpha': 0.1, 'binarize': 0.5}",0.908877,0.962264,0.925524,0.962573,0.981217,0.948091,0.026664,1
2,0.009624,0.002339,0.007826,0.002218,0.1,1.0,"{'alpha': 0.1, 'binarize': 1.0}",0.750308,0.805463,0.867217,0.865441,0.842027,0.826091,0.043960,11
3,0.007181,0.003566,0.010513,0.001721,0.5,0.0,"{'alpha': 0.5, 'binarize': 0.0}",0.908877,0.943699,0.925524,0.962573,0.981217,0.944378,0.025708,3
4,0.008649,0.001288,0.007074,0.002067,0.5,0.5,"{'alpha': 0.5, 'binarize': 0.5}",0.908877,0.943699,0.925524,0.962573,0.981217,0.944378,0.025708,3
5,0.010090,0.002751,0.007988,0.003726,0.5,1.0,"{'alpha': 0.5, 'binarize': 1.0}",0.750308,0.805463,0.867217,0.865441,0.842027,0.826091,0.043960,11
6,0.009263,0.003337,0.004760,0.002876,1.0,0.0,"{'alpha': 1.0, 'binarize': 0.0}",0.908877,0.925272,0.925524,0.962573,0.962573,0.936964,0.021763,6
7,0.006946,0.003569,0.009051,0.003104,1.0,0.5,"{'alpha': 1.0, 'binarize': 0.5}",0.908877,0.925272,0.925524,0.962573,0.981217,0.940693,0.026837,5
8,0.008266,0.001046,0.009501,0.004154,1.0,1.0,"{'alpha': 1.0, 'binarize': 1.0}",0.750308,0.805463,0.867217,0.865441,0.842027,0.826091,0.043960,11
9,0.005576,0.003016,0.009495,0.002378,1.5,0.0,"{'alpha': 1.5, 'binarize': 0.0}",0.908877,0.925272,0.869925,0.962573,0.962573,0.925844,0.034966,8
10,0.005643,0.002301,0.009391,0.000672,1.5,0.5,"{'alpha': 1.5, 'binarize': 0.5}",0.908877,0.925272,0.925524,0.962573,0.962573,0.936964,0.021763,6
11,0.008465,0.000796,0.006997,0.003905,1.5,1.0,"{'alpha': 1.5, 'binarize': 1.0}",0.750308,0.805463,0.867217,0.865441,0.842027,0.826091,0.043960,11
12,0.007129,0.004295,0.007961,0.004236,2.0,0.0,"{'alpha': 2.0, 'binarize': 0.0}",0.908877,0.906935,0.832377,0.944023,0.962573,0.910957,0.044616,10
13,0.005116,0.002432,0.009138,0.002810,2.0,0.5,"{'alpha': 2.0, 'binarize': 0.5}",0.908877,0.925272,0.869925,0.962573,0.962573,0.925844,0.034966,8
14,0.003858,0.002784,0.009718,0.002389,2.0,1.0,"{'alpha': 2.0, 'binarize': 1.0}",0.750308,0.805463,0.867217,0.865441,0.842027,0.826091,0.043960,11